add_newline = false

format = """\
	$directory\
	$git_branch\
	$git_status\
	$kubernetes\
	$golang\
	$line_break\
	$cmd_duration\
	$character\
"""

[character]      # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[V](bold green) "

[hostname]
ssh_only = true
prefix = "⟪"
suffix = "⟫"
disabled = false

[golang]
disabled = true

[kubernetes]
symbol = ""
style = "dimmed green"
disabled = false

[aws]
displayed_items = "profile"

