# env
source ~/.env

# alias
source $HOME/.alias.sh

# path
export PATH=$PATH:/Users/jbaker/bin:/Users/jbaker/go/bin:/usr/local/sbin:/usr/local/opt:/Users/jbaker/Library/Python/3.8/bin

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# Prompt
autoload -U promptinit
promptinit
setopt PROMPT_SUBST
setopt TRANSIENT_RPROMPT

# Other options
setopt rmstarsilent
setopt interactivecomments

# Keybinding
bindkey -e
bindkey '^i' expand-or-complete-prefix
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey "${terminfo[kcbt]}" reverse-menu-complete
bindkey "${terminfo[kdch1]}" delete-char
autoload -U select-word-style
select-word-style bash

# Auto-completion
autoload -U compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_COMPLETION_TRIGGER=','

# zoxide
eval "$(zoxide init zsh)"

# hub cli, github client
eval "$(hub alias -s)"

setopt COMPLETE_ALIASES

exit_zsh() { exit }
zle -N exit_zsh
bindkey '^D' exit_zsh

alcs () {
    alacritty-colorscheme -a /Users/jbaker/.config/alacritty/colors/"$1".yaml
}

alop () {
    sed -i .bak "s/^background_opacity: *.*/background_opacity: ${1}/" $HOME/.config/alacritty/alacritty.yml
}

kc () {
    if [ -n "$1" ]; then
        case "$1" in
        eng-dev)
        REGION="us-east-1"
	      PROFILE="developers"
        CONTEXT="eks_eng-dev_developer"
        ;;
        dev)
        REGION="us-east-1"
        PROFILE="developers"
        CONTEXT="eks_dev1_developer"
        ;;
        staging)
        REGION="us-west-2"
        PROFILE="platform-staging-admin"
        CONTEXT="eks_ripplenet-staging_admin"
        ;;
        prod)
        REGION="eu-west-2"
        CONTEXT="eks_ripplenet-prod_admin"
        PROFILE="ripplenet-prod-admin"
        ;;
        rnc)
        REGION="eu-west-2"
        CONTEXT="eks_rnc-prod_admin"
        PROFILE="ripplenet-xcurrent-prod-admin"
        ;;
        esac
    fi

    export AWS_SDK_LOAD_CONFIG=true
    export AWS_DEFAULT_REGION=$REGION
    export AWS_PROFILE=$PROFILE

    if aws sts get-caller-identity &>/dev/null;
    then
	    :
    else
      #expectsts "$(gpg --decrypt $HOME/.secret/pword.asc 2>/dev/null)" "$PROFILE" "$REGION"
	    vault_get_sts_token -r $PROFILE --region $REGION
    fi

    if [ -n "$2" ];
    then
        NAMESPACE=${2}
	      kubie ctx "$CONTEXT" -n "$NAMESPACE" 
    else
        if [ -n "$NAMESPACE" ]; then
               NAMESPACE=""
        fi
	      kubie ctx "$CONTEXT" 
    fi
    unset AWS_SDK_LOAD_CONFIG
    unset AWS_DEFAULT_REGION
    unset AWS_PROFILE

}

alias kns="kubie ns"

source <(kubectl completion zsh)
source "$HOME/.kubectl_fzf.plugin.zsh"
# OPS config
export OPS_DIR="$HOME/.ops"

export PATH="$HOME/.ops/bin:$PATH"
export PATH="/usr/local/opt/util-linux/bin:/usr/local/Cellar/bash/5.1.4/bin:$PATH"
eval "$(starship init zsh)"
